decks = {
    "Star-Wars": [
        "Obi-Wan Kenobi",
        "Qui-Gon Jinn",
        "Padme",
        "Anakin",
        "Yoda",
        "Mace Windu",
        "Ki-Adi Mundi",
        "Kit Fisto",
        "Plo Koon",
        "Aayla Secura",
        "Shaak Ti",
        "Darth Maul",
        "Emporer Palpatine",
        "R2-D2",
        "C-3PO",
        "Watto",
        "Shmi Skywalker",
        "Nute Gunray",
        "Battle Droid",
        "Super Battle Droid",
        "Droideka",
        "Jar Jar Binks",
        "Boss Nass",
        "Zam Wessel",
        "Jango Fett",
        "Dexter Jester",
        "Count Dooku",
        "Poggle the Lesser",
        "Clone Trooper",
        "Commander Cody",
        "Captain Rex",
        "The Younglings",
        "Darth Vader",
        "Tusken Raiders",
        "General Grievous",
        "Luke Skywalker",
        "Leia Organa",
        "Han Solo",
        "Chewbacca",
        "Greedo",
        "Boba Fett",
        "Stormtrooper",
        "Death Trooper",
        "Grand Moff Tarkin",
        "Jabba the Hutt",
        "Aunt Beru",
        "Uncle Owen",
        "Jawa",
        "Lando Calrissian",
        "Wampa",
        "Bantha",
        "Womp Rat",
        "Admiral Akbar",
        "Rey",
        "Finn",
        "Poe",
        "Kylo Ren",
        "BB-8",
        "Snoke",
        "Rose Tico",
        "General Hux",
        "D-O",
        "Maz Kanata",
        "Babu Frik",
        "Admiral Holdo",
        "Ahsoka",
        "Fives",
        "Savage Oppress",
        "Asajj Ventress",
        "Gregor",
        "Wolfe",
        "Mother Talzin",
        "Nightbrothers",
        "Nightsisters",
        "Cad Bane",
        "Fennec Shand",
        "Echo",
        "Wrecker",
        "Tech",
        "Crosshair",
        "Omega",
        "Cal Kestis",
        "BD-1",
        "Cere",
        "Trilla",
        "Merrin",
        "Greeze",
        "Jaro Tapal",
        "Endo Cordova",
        "Reva",
        "Kanan Jarrus",
        "Ezra Bridger",
        "Hera Syndulla",
        "Chopper",
        "Sabine",
        "Zeb",
        "Grand Admiral Thrawn",
        "The Mandolorian",
        "Grogu",
        "Kuill",
        "Cara Dune",
        "Greef Carga",
        "Haja",
        "Moff Gideon",
        "Bo Katan",
        "Pre Vizla",
        "The Armorer",
        "Gonk Droid",
        "Darth Jar Jar",
        "Tatooine",
        "Coruscant",
        "Mustafar",
        "Kamino",
        "Hoth",
        "Endor",
        "Illum",
        "Lothal",
        "Lightsaber",
        "Blaster",
        "The Force",
        "The Light Side",
        "The Dark Side",
        "Beskar",
        "Wrist Rockets",
        "The Dark Saber",
        "Kaiber Crystal",
        "Jetpack",
        "Ray Shield",
        "Millenium Falcon",
        "Death Star",
        "The Ghost",
        "Starkiller Base",
        "X-wing",
        "Y-wing",
        "Tie Fighter",
        "Bendu"
    ],
    "Marvel": [
        "Captain America",
        "Iron Man",
        "The Hulk",
        "Thor",
        "Black Widow",
        "Hawkeye",
        "Nick Fury",
        "Maria Hill",
        "Loki",
        "The Chitauri",
        "Pepper Pots",
        "War Machine",
        "Howard Stark",
        "Bruce Banner",
        "Whiplash",
        "Peggy Carter",
        "Happy Hogan",
        "Bucky Barnes",
        "Red Skull",
        "The Falcon",
        "Sharon Carter",
        "Phil Coulson",
        "Spider-Man",
        "Ant Man",
        "Black Panther",
        "Scarlet Witch",
        "The Wasp",
        "Jimmy Woo",
        "Zemo",
        "Vision",
        "JARVIS",
        "King T'Chaka",
        "Okoye",
        "Odin",
        "Lady Sif",
        "Jane Foster",
        "Eric Selvig",
        "Darcy Lewis",
        "Heimdall",
        "Frigga",
        "Frost Giants",
        "The Destroyer",
        "The Grandmaster",
        "Grand Inquisitor",
        "Hela",
        "Valkyrie",
        "Korg",
        "Miek",
        "Skurge",
        "Surter",
        "The Collector",
        "Abomination",
        "General Ross",
        "Thanos",
        "Ultron",
        "Quicksilver",
        "Agatha Harkness",
        "Laura Barton",
        "Hank Pym",
        "Janet Van Dyne",
        "Cassie Lang",
        "Yellowjacket",
        "Ghost",
        "Doctor Strange",
        "Wong",
        "The Ancient One",
        "Mordo",
        "Christine Palmer",
        "Dormammu",
        "America Chavez",
        "Mr. Fantastic",
        "Invisible Woman",
        "The Thing",
        "Human Torch",
        "Dr. Doom",
        "Galactus",
        "Professor X",
        "Wolverine",
        "Deadpool",
        "Black Bolt",
        "Captain Marvel",
        "MJ",
        "Ned",
        "Aunt May",
        "Vulture",
        "Flash Thompson",
        "Mysterio",
        "The Skrulls",
        "J Jonah Jameson",
        "Doctor Octopus",
        "Green Goblin",
        "Venom",
        "Electro",
        "Sandman",
        "The Lizard",
        "Goose",
        "Maria Rambeau",
        "Monica Rambeau",
        "The Kree",
        "Shuri",
        "Killmonger",
        "M'Baku",
        "Starlord",
        "Gamora",
        "Groot",
        "Drax",
        "Rocket Racoon",
        "Yondu",
        "Ronan the Accuser",
        "The Nova Corps",
        "Nebula",
        "The Ravagers",
        "Mantis",
        "Ego the Living Planet",
        "Taserface",
        "Baby Groot",
        "Ebony Maw",
        "Proxima Midnight",
        "Cull Obsidian",
        "Corvus Glave",
        "Ditri",
        "Morgan Stark",
        "Sersi",
        "Gilgamesh",
        "Icarus",
        "Sprite",
        "Thena",
        "Makarri",
        "Kingo",
        "Druig",
        "Ajak",
        "Phastos",
        "Dane Whitman",
        "Arishem",
        "The Celestials",
        "The Deviants",
        "Shang Chi",
        "Katy Chen",
        "Xu Xialing",
        "The Mandarin",
        "Trevor",
        "Maurice",
        "Razorfist",
        "The Great Protector",
        "The Dweller in the Darkness",
        "Yelena Belova",
        "Red Guardian",
        "Melina Vostokoff",
        "Taskmaster",
        "Morbius",
        "Miles Morales",
        "Mephisto",
        "FRIDAY",
        "Mobius",
        "Miss Minutes",
        "Kate Bishop",
        "The Watcher",
        "Billy and Tommy",
        "Silver Surfer",
        "Kang the Conqueror" 
    ],
    "Book-of-Mormon": [
        "Nephi",
        "Lehi",
        "Laman",
        "Sam",
        "Laban",
        "Lemuel",
        "Zoram",
        "Ishmael",
        "Sariah",
        "Brass Plates",
        "Laban's Sword",
        "The wilderness",
        "Jerusalen",
        "The rod of iron",
        "The Liahona",
        "The Great and Spacious Building",
        "Mist of Darkness",
        "Joseph son of Joseph",
        "Jacob son of Lehi",
        "Land of Nephi",
        "The Promised Land",
        "Sherem",
        "Olive Tree",
        "Vinyard",
        "Enos",
        "The Book of Mormon",
        "The Gold Plates",
        "Jarom",
        "Omni",
        "Mosiah I",
        "King Benjamin",
        "Mosiah II",
        "Zerehemla",
        "Mulekites",
        "Nephites",
        "Lamanites",
        "King Zedekiah",
        "Jaredites",
        "King Noah",
        "King Limhi",
        "King Zenith",
        "Abinadi",
        "Alma the Elder",
        "Alma the Younger",
        "The Sons of Mosiah",
        "Ammon",
        "Ammonihah",
        "King Lamoni",
        "Abish",
        "Gideon",
        "The Wicked Priests",
        "Nehor",
        "Ramiumpton",
        "Amulek",
        "Zeezrom",
        "Mormon",
        "Anti-Nephi-Lehites",
        "Korihor",
        "Zenos, Zenock, and Neum",
        "Helaman son of Alma",
        "Shiblon",
        "Corianton",
        "Captain Moroni",
        "The stripling warriors",
        "Tiancum",
        "Amalickiah",
        "Title of Liberty",
        "Pahoran",
        "Samuel the Lamanite",
        "Nephi and Lehi sons of Helaman",
        "Nephi son of Nephi",
        "The Three Nephites",
        "The Land of Bountiful",
        "Moroni son of Mormon",
        "Jared",
        "The Brother of Jared",
        "Ether",
        "Land of Desolation",
        "Gadianton Robbers",
        "Hill Cumorah",
        "Angels",
    ]
}