decks = {
    "Star Wars: Movies": [
        "Obi-Wan Kenobi",
        "Qui-Gon Jinn",
        "Padme",
        "Anakin",
        "Yoda",
        "Mace Windu",
        "Ki-Adi Mundi",
        "Kit Fisto",
        "Aayla Secura",
        "Shaak Ti",
        "Darth Maul",
        "Emporer Palpatine",
        "R2-D2",
        "C-3PO",
        "Watto",
        "Shmi Skywalker",
        "Nute Gunray",
        "Battle Droid",
        "Super Battle Droid",
        "Droideka",
        "Jar Jar Binks",
        "Boss Nass",
        "Zam Wessel",
        "Jango Fett",
        "Dexter Jester",
        "Count Dooku",
        "Poggle the Lesser",
        "Clone Trooper",
        "Commander Cody",
        "The Younglings",
        "Darth Vader",
        "Tusken Raiders",
        "General Grievous",
        "Luke Skywalker",
        "Leia Organa",
        "Han Solo",
        "Chewbacca",
        "Greedo",
        "Boba Fett",
        "Stormtrooper",
        "Jabba the Hutt",
        "Aunt Beru",
        "Uncle Owen",
        "Jawa",
        "Lando Calrissian",
        "Wampa",
        "Bantha",
        "Womp Rat",
        "Admiral Akbar",
        "Rey",
        "Finn",
        "Poe",
        "Kylo Ren",
        "BB-8",
        "Snoke",
        "Rose Tico",
        "General Hux",
        "D-O",
        "Maz Kanata",
        "Babu Frik",
        "Admiral Holdo",
        "Lightsaber",
        "Blaster",
        "The Force",
        "The Light Side",
        "The Dark Side",
        "Beskar",
        "Wrist Rockets",
        "Kaiber Crystal",
        "Jetpack",
        "Ray Shield",
        "Millenium Falcon",
        "Death Star",
        "Starkiller Base",
        "X-wing",
        "Y-wing",
        "Tie Fighter",
        "Grand Moff Tarkin",
        "Gonk Droid",
        "Tatooine",
        "Coruscant",
        "Mustafar",
        "Kamino",
        "Hoth",
        "Endor",
    ],
    "Star Wars: Clone Wars": [
        "Plo Koon",
        "Captain Rex",
        "Death Trooper",
        "Ahsoka",
        "Fives",
        "Savage Oppress",
        "Asajj Ventress",
        "Gregor",
        "Wolfe",
        "Mother Talzin",
        "Nightbrothers",
        "Nightsisters",
        "Cad Bane",
        "Fennec Shand",
        "Echo",
        "Wrecker",
        "Tech",
        "Crosshair",
        "Illum",
        "Bo Katan",
        "Pre Vizla",
        "The Dark Saber",
    ],
    "Star Wars: Rebels": [
        "Kanan Jarrus",
        "Ezra Bridger",
        "Hera Syndulla",
        "Chopper",
        "Sabine",
        "Zeb",
        "Grand Admiral Thrawn",
        "The Ghost",
        "Bendu",
        "Lothal",
        "Inquisitors",
        "The Grand Inquisitor",
    ],
    "Star Wars: Bad Batch": [
        "Omega",
    ],
    "Star Wars: Jedi Games": [
        "Cal Kestis",
        "BD-1",
        "Cere",
        "Trilla",
        "Merrin",
        "Greeze",
        "Mantis",
        "Jaro Tapal",
        "Endo Cordova",
        "Ninth Sister",
        "Jedah",
        "Koboh",
    ],
    "Star Wars: Kenobi": [
        "Reva",
        "Haja",
    ],
    "Star Wars: The Mandalorian": [
        "The Mandolorian",
        "Grogu",
        "Kuill",
        "Cara Dune",
        "Greef Carga",
        "Moff Gideon",
        "The Armorer",
        "IG-11",
    ],
    "Marvel": [
        "Captain America",
        "Iron Man",
        "The Hulk",
        "Thor",
        "Black Widow",
        "Hawkeye",
        "Nick Fury",
        "Maria Hill",
        "Loki",
        "The Chitauri",
        "Pepper Pots",
        "War Machine",
        "Howard Stark",
        "Bruce Banner",
        "Whiplash",
        "Peggy Carter",
        "Happy Hogan",
        "Bucky Barnes",
        "Red Skull",
        "The Falcon",
        "Sharon Carter",
        "Phil Coulson",
        "Spider-Man",
        "Ant Man",
        "Black Panther",
        "Scarlet Witch",
        "The Wasp",
        "Jimmy Woo",
        "Zemo",
        "Vision",
        "JARVIS",
        "King T'Chaka",
        "Okoye",
        "Odin",
        "Lady Sif",
        "Jane Foster",
        "Eric Selvig",
        "Darcy Lewis",
        "Heimdall",
        "Frigga",
        "Frost Giants",
        "The Destroyer",
        "The Grandmaster",
        "Grand Inquisitor",
        "Hela",
        "Valkyrie",
        "Korg",
        "Miek",
        "Skurge",
        "Surter",
        "The Collector",
        "Abomination",
        "General Ross",
        "Thanos",
        "Ultron",
        "Quicksilver",
        "Agatha Harkness",
        "Laura Barton",
        "Hank Pym",
        "Janet Van Dyne",
        "Cassie Lang",
        "Yellowjacket",
        "Ghost",
        "Doctor Strange",
        "Wong",
        "The Ancient One",
        "Mordo",
        "Christine Palmer",
        "Dormammu",
        "America Chavez",
        "Mr. Fantastic",
        "Invisible Woman",
        "The Thing",
        "Human Torch",
        "Dr. Doom",
        "Galactus",
        "Professor X",
        "Wolverine",
        "Deadpool",
        "Black Bolt",
        "Captain Marvel",
        "MJ",
        "Ned",
        "Aunt May",
        "Vulture",
        "Flash Thompson",
        "Mysterio",
        "The Skrulls",
        "J Jonah Jameson",
        "Doctor Octopus",
        "Green Goblin",
        "Venom",
        "Electro",
        "Sandman",
        "The Lizard",
        "Goose",
        "Maria Rambeau",
        "Monica Rambeau",
        "The Kree",
        "Shuri",
        "Killmonger",
        "M'Baku",
        "Starlord",
        "Gamora",
        "Groot",
        "Drax",
        "Rocket Racoon",
        "Yondu",
        "Ronan the Accuser",
        "The Nova Corps",
        "Nebula",
        "The Ravagers",
        "Mantis",
        "Ego the Living Planet",
        "Taserface",
        "Baby Groot",
        "Ebony Maw",
        "Proxima Midnight",
        "Cull Obsidian",
        "Corvus Glave",
        "Ditri",
        "Morgan Stark",
        "Sersi",
        "Gilgamesh",
        "Icarus",
        "Sprite",
        "Thena",
        "Makarri",
        "Kingo",
        "Druig",
        "Ajak",
        "Phastos",
        "Dane Whitman",
        "Arishem",
        "The Celestials",
        "The Deviants",
        "Shang Chi",
        "Katy Chen",
        "Xu Xialing",
        "The Mandarin",
        "Trevor",
        "Maurice",
        "Razorfist",
        "The Great Protector",
        "The Dweller in the Darkness",
        "Yelena Belova",
        "Red Guardian",
        "Melina Vostokoff",
        "Taskmaster",
        "Morbius",
        "Miles Morales",
        "Mephisto",
        "FRIDAY",
        "Mobius",
        "Miss Minutes",
        "Kate Bishop",
        "The Watcher",
        "Billy and Tommy",
        "Silver Surfer",
        "Kang the Conqueror" 
    ],
    "Book of Mormon": [
        "Nephi",
        "Lehi",
        "Laman",
        "Sam",
        "Laban",
        "Lemuel",
        "Zoram",
        "Ishmael",
        "Sariah",
        "Brass Plates",
        "Laban's Sword",
        "The wilderness",
        "Jerusalen",
        "The rod of iron",
        "The Liahona",
        "The Great and Spacious Building",
        "Mist of Darkness",
        "Joseph son of Joseph",
        "Jacob son of Lehi",
        "Land of Nephi",
        "The Promised Land",
        "Sherem",
        "Olive Tree",
        "Vinyard",
        "Enos",
        "The Book of Mormon",
        "The Gold Plates",
        "Jarom",
        "Omni",
        "Mosiah I",
        "King Benjamin",
        "Mosiah II",
        "Zerehemla",
        "Mulekites",
        "Nephites",
        "Lamanites",
        "King Zedekiah",
        "Jaredites",
        "King Noah",
        "King Limhi",
        "King Zenith",
        "Abinadi",
        "Alma the Elder",
        "Alma the Younger",
        "The Sons of Mosiah",
        "Ammon",
        "Ammonihah",
        "King Lamoni",
        "Abish",
        "Gideon",
        "The Wicked Priests",
        "Nehor",
        "Ramiumpton",
        "Amulek",
        "Zeezrom",
        "Mormon",
        "Anti-Nephi-Lehites",
        "Korihor",
        "Zenos, Zenock, and Neum",
        "Helaman son of Alma",
        "Shiblon",
        "Corianton",
        "Captain Moroni",
        "The stripling warriors",
        "Tiancum",
        "Amalickiah",
        "Title of Liberty",
        "Pahoran",
        "Samuel the Lamanite",
        "Nephi and Lehi sons of Helaman",
        "Nephi son of Nephi",
        "The Three Nephites",
        "The Land of Bountiful",
        "Moroni son of Mormon",
        "Jared",
        "The Brother of Jared",
        "Ether",
        "Land of Desolation",
        "Gadianton Robbers",
        "Hill Cumorah",
        "Angels",
    ],
    "Things": [
        "apple",
        "book",
        "car",
        "dog",
        "egg",
        "fork",
        "guitar",
        "house",
        "internet",
        "jacket",
        "key",
        "lamp",
        "mouse",
        "notebook",
        "orange",
        "pencil",
        "quilt",
        "radio",
        "shoe",
        "table",
        "umbrella",
        "vase",
        "watch",
        "xylophone",
        "yarn",
        "zebra",
        "plane",
        "baseball",
        "camera",
        "desk",
        "earphones",
        "flower",
        "globe",
        "hat",
        "ice cream",
        "jelly",
        "kangaroo",
        "laptop",
        "mirror",
        "necklace",
        "oven",
        "piano",
        "quiche",
        "rug",
        "socks",
        "television",
        "ukulele",
        "violin",
        "whistle",
        "yogurt",
        "zeppelin",
        "clock",
        "backpack",
        "calculator",
        "dumbbell",
        "earrings",
        "fan",
        "glasses",
        "headphones",
        "iron",
        "juice",
        "kite",
        "lampshade",
        "marker",
        "nail polish",
        "nails",
        "orange juice",
        "pillow",
        "quill",
        "remote",
        "scissors",
        "t-shirt",
        "umbilical cord",
        "vest",
        "wallet",
        "yacht",
        "apartment",
        "balloon",
        "computer",
        "dictionary",
        "eraser",
        "flashlight",
        "grapefruit",
        "hanger",
        "ice",
        "jellyfish",
        "keyboard",
        "lemon",
        "microphone",
        "necktie",
        "ocean",
        "blanket",
        "ruler",
        "stapler",
        "toothbrush",
        "underwear",
        "bow",
        "whisk",
        "yoga mat",
        "accordion",
        "backgammon",
        "calendar",
        "donut",
        "eggplant",
        "fishing rod",
        "golf club",
        "stick",
        "insect",
        "puzzle",
        "pouch",
        "lawnmower",
        "microscope",
        "note",
        "pepperoni",
        "quartz",
        "roller skates",
        "stamp",
        "toothpaste",
        "whistle",
        "almond",
        "bag",
        "cake",
        "donkey",
        "ear",
        "football",
        "pick",
        "horse",
        "ice skates",
        "jumper",
        "kettle",
        "ladder",
        "mug",
        "notebook",
        "peanut butter",
        "rollerblades",
        "sandwich",
        "towel",
        "whiskey",
        "plant",
        "zipper",
        "apple pie",
        "banana",
        "cat",
        "desk lamp",
        "earmuffs",
        "football helmet",
        "grapes",
        "ironing board",
        "jacket",
        "knife",
        "milk",
        "note pad",
        "peas",
        "quinoa",
        "sand",
        "toaster",
        "vase",
        "whistle",
        "yolk",
        "ziploc bag",
        "armchair",
        "barbecue",
        "candle",
        "drum",
        "easel",
        "football field",
        "grill",
        "horse saddle",
        "island",
        "jeans",
        "kayak",
        "magnifying glass",
        "nightstand",
        "pepper",
        "rose",
        "salt",
        "vintage car",
        "water bottle",
        "yoga ball",
        "arrow",
        "basketball",
        "cat food",
        "dog leash",
        "envelope",
        "drive",
        "gloves",
        "hotdog",
        "jump rope",
        "sink",
        "lamp post",
        "mango",
        "newspaper",
        "photos",
        "photo album",
        "quicksand",
        "rosemary",
        "scarf",
        "taco",
        "vacuum",
        "spoon",
        "x-ray",
        "squash",
        "zoo",
        "alarm",
        "bat",
        "caterpillar",
        "dog bed",
        "pen",
        "fountain",
        "gum",
        "hot tub",
        "building",
        "jukebox",
        "laser",
        "microwave",
        "night light",
        "panda bear",
        "fabric",
        "rope",
        "soup",
        "tire swing",
        "workout bench",
        "zucchini",
        "asparagus",
        "basket",
        "dumbbell set",
        "electric razor",
        "frying pan",
        "gummy bears",
        "hot plate",
        "pool",
        "juicer",
        "string",
        "mascara",
        "pasta",
        "bike",
        "surfboard",
        "treadmill",
        "chair",
        "needle",
        "avocado",
        "basketball hoop",
        "coconut",
        "dresser",
        "gummy worms",
        "hula hoop",
        "insect repellent",
        "juice box",
        "laundry detergent",
        "mashed potatoes",
        "nail file",
        "pizza",
        "rolling pin",
        "skateboard",
        "sunscreen",
        "trampoline",
        "vending machine",
        "yoga strap",
        "baseball glove",
        "dog collar",
        "boots",
        "jeep",
        "lawn chair",
        "milk carton",
        "paper",
        "rubber duck",
        "shampoo",
        "toothpick",
        "toy",
        "yoga swing",
        "blocks",
        "canvas",
        "gym bag",
        "hiking",
        "fridge",
        "purse",
        "rubber band",
        "shaving cream",
        "train",
        "yoga block",
        "hoodie",
        "jersey",
        "car tire",
        "diaper",
        "footstool",
        "gym mat",
        "jumping rope",
        "kitchen timer",
        "sprinkler",
        "rubber gloves",
        "shower curtain",
        "toothpaste tube",
        "mattress",
        "dice",
        "mixer",
        "forklift",
        "gym shoes",
        "insect bite",
        "kitchen utensils",
        "fertilizer",
        "mitten",
        "shower gel",
        "stool",
        "yoga pants",
        "engine",
        "pitcher",
        "window",
        "shaver",
        "fork",
        "gym shorts",
        "jungle gym",
        "bowl",
        "peppermint",
        "rubber stopper",
        "showerhead",
    ],
    "Video Games: Misc": [
        "Pac Man",
        "Tetris",
        "Tetromino",
        "Pong",
        "Galaga",
        "Space Invaders",
        "Snake",
        "Terraria",
        "The Eye of Cthulhu",
        "Eater of Worlds",
        "Brain of Cthulhu",
        "Queen Bee",
        "Skeletron",
        "Wall of Flesh",
        "Moon Lord",
        "King Slime",
        "Queen Slime",
        "Mimic",
        "Guitar Hero",
        "Minecraft",
        "Plant vs Zombies",
        "Pea Shooter",
        "Sunflower",
        "Cherry Bomb",
        "Wall-nut",
        "Potato Mine",
        "Portal Gun",
        "The Keyblade",
        "The Energy Sword",
        "Assault Rifle",
        "Master Chief",
        "Cortana",
        "Cake",
        "Companion Cube",
        "The Zenith",
        "Cave Johnson",
        "Portal",
        "Mortal Kombat",
        "Sub-Zero",
        "Grand Theft Auto",
        "Doom",
        "Scorpion",
        "Elder Scrolls",
        "Hadouken",
        "Shoryuken",
        "Raiden",
        "Doom Guy",
        "Spyro",
        "Crash Bandicoot",
        "Fall Guys",
        "Rocket League",
        "Gang Beasts",
        "Fortnite",
        "CS:GO",
        "Valorant",
        "League of Legends",
        "Overwatch",
        "Jedi: Fallen Order",
        "Don't Starve",
        "Charlie",
        "Assassin's Creed",
        "Amnesia: The Dark Descent",
        "The Last of Us",
        "Among Us",
        "The Binding of Isaac",
        "Bloons Tower Defense",
        "Dead Cells",
        "Hollow Knight",
        "Doki Doki Literature Club",
        "Undertale",
        "Delta Rune",
        "Jackbox Party Pack",
        "Phasmophobia",
        "Goat Simulator",
        "Resident Evil",
        "Metal Gear",
        "Lego",
        "The Witness",
        "The Stanley Parable",
        "The Looker",
        "No Man's Sky",
        "OneShot",
        "Little Nightmares",
        "Plague Inc",
        "Poly Bridge",
        "Battlefront",
        "Tomb Raider",
        "Superliminal",
        "Kindergarten",
        "Kingdom Hearts",
        "The Witcher",
        "Ultimate Chicken Horse",
        "Dark Souls",
        "Elden Ring",
        "Sekiro",
        "Bloodborne",
        "Plague Tale",
    ],
    "Video Games: Nintendo": [
        "Matt",
        "Mario",
        "Luigi",
        "Peach",
        "Bowser",
        "Daisy",
        "Toad",
        "Yoshi",
        "Shy Guy",
        "Kamek",
        "Koopa Troopa",
        "Goomba",
        "Piranha Plant",
        "Boo",
        "Wario",
        "Waluigi",
        "Thwomp",
        "Whomp",
        "Dry Bones",
        "Bob-omb",
        "Birdo",
        "King Boo",
        "Toadette",
        "Bowser Jr.",
        "Donkey Kong",
        "Rosalina",
        "Luma",
        "Bullet Bill",
        "Lakitu",
        "Hammer Bro",
        "Chain Chomp",
        "Diddy Kong",
        "Mushroom",
        "Fire Flower",
        "Star",
        "Green Shell",
        "Red Shell",
        "Blue Shell",
        "Banana Peel",
        "Rainbow Road",
        "Mario Kart",
        "Super Mario Bros.",
        "Super Smash Bros.",
        "Super Mario Galaxy",
        "Super Mario 64",
        "Super Mario Sunshine",
        "Super Mario Odyssey",
        "Luigi's Mansion",
        "Mario Party",
        "Professor E. Gadd",
        "1-UP Mushroom",
        "Cappy",
        "Captain Toad",
        "? Block",
        "Link",
        "Zelda",
        "Ganon",
        "Sheik",
        "Impa",
        "Tri Force",
        "Ocarina of Time",
        "Master Sword",
        "Navi",
        "The Great Deku Tree",
        "Deku Scrub",
        "Korok",
        "Guardian",
        "Bokoblin",
        "Moblin",
        "Tingle",
        "Goron",
        "Zora",
        "Rito",
        "Midna",
        "Gerudo",
        "Hyrule",
        "Urbosa",
        "Revali",
        "Mipha",
        "Daruk",
        "Beetle",
        "Epona",
        "Temple of Time",
        "Great Fairy",
        "Shrine",
        "Hylian Shield",
        "Hookshot",
        "Breath of the Wild",
        "Skyward Sword",
        "Twilight Princess",
        "Wind Waker",
        "Majora's Mask",
        "A Link To The Past",
        "Hylia",
        "Hestu",
        "Wolf Link",
        "Dark Link",
        "Animal Crossing",
        "Villager",
        "Isabelle",
        "Tom Nook",
        "Timmy and Tommy",
        "Blathers",
        "Celeste",
        "K.K. Slider",
        "Kirby",
        "Meta Knight",
        "King Dedede",
        "Waddle Dee",
        "Waddle Doo",
        "Charizard",
        "Pikachu",
        "Jigglypuff",
        "Squirtle",
        "Ivysaur",
        "Ash",
        "Mewtwo",
        "Lucario",
        "Greninja",
        "Pichu",
        "Snorlax",
        "Diglett",
        "Mew",
        "Eevee",
        "Pokemon",
        "Pokeball",
        "Meowth",
        "Samus",
        "Zero Suit Samus",
        "Fox",
        "Falco",
        "Wolf",
        "Pikmin",
        "Captain Falcon",
        "Ness",
        "Lucas",
        "Pit",
        "Dark Pit",
        "Olimar",
        "Snake",
        "Ike",
        "Pokemon Trainer",
        "Palutena",
        "Miis",
        "Wii Fit Trainer",
        "Mega Man",
        "Zero",
        "Dr. Light",
        "Sigma",
        "Sonic",
        "Shadow",
        "Knuckles",
        "Tails",
        "Amy",
        "Blaze",
        "Dr. Eggman",
        "Green Hill Zone",
        "Golden Rings",
        "Chaos Emeralds",
        "Peaches Castle",
        "Bowser's Castle",
        "Ganon's Castle",
        "Kakariko Village",
        "Warp Pipe",
        "Inkling",
        "NES",
        "SNES",
        "N64",
        "Gamecube",
        "Wii",
        "Wii U",
        "Switch",
        "Gameboy",
        "DS",
        "Wiimote",
        "Joycon",
        "Master Hand",
        "Dark Samus",
        "Incineroar",
        "King K. Rool",
        "Banjo & Kazooie",
        "Ridley",
        "Mr. Game & Watch",
        "Ice Climbers",
        "Galeem",
        "Dr. Mario",
        "Smash Ball",
        "R.O.B.",
        "Duck Hunt",
        "Bayonetta",
    ],
    "Video Games: Minecraft": [
        "Steve",
        "Alex",
        "Enderman",
        "Creeper",
        "Ender Dragon",
        "Zombie",
        "Skeleton",
        "Spider",
        "Ghast",
        "Magma Cube",
        "Slime",
        "Witch",
        "Villager",
        "Iron Golem",
        "Snow Golem",
        "Blaze",
        "Wither",
        "Wither Skeleton",
        "Guardian",
        "Elder Guardian",
        "Shulker",
        "Endermite",
        "Cow",
        "Pig",
        "Sheep",
        "Chicken",
        "Squid",
        "Glow Squid",
        "Phantom",
        "Mooshroom",
        "Nether",
    ],
    "Video Games: Bloons": [
        "Dart Monkey",
        "Tack Shooter",
        "Ice Monkey",
        "Glue Gunner",
        "Wizard Monkey",
        "Super Monkey",
        "Ninja Monkey",
        "Alchemist",
        "Banana Farm",
        "Spike Factory",
        "Quincy son of Quincy",
        "Gwendolin",
        "Obyn Greenfoot",
        "Benjamin",
        "MOAB",
        "Bloons",
    ],
    "Video Games: FNAF": [
        "Freddy",
        "Bonnie",
        "Chica",
        "Foxy",
        "Toy Freddy",
        "Toy Bonnie",
        "Toy Chica",
        "Mangle",
        "Balloon Boy",
        "Dee Dee",
        "Withered Chica",
        "Withered Bonnie",
        "The Puppet",
        "Golden Freddy",
        "Springtrap",
        "Phantom Mangle",
        "Phantom Freddy",
        "Phantom Balloon Boy",
        "Nightmare Freddy",
        "Nightmare Bonnie",
        "Nightmare Chica",
        "Nightmare Golden Freddy",
        "Lefty",
        "Nightmare Balloon Boy",
        "Old Man Consequences",
        "Baby",
        "Ballora",
        "Funtime Foxy",
        "Ennard",
        "Trash and the Gang",
        "Freddles",
        "Mediocre Melodies",
        "Music Man",
        "Funtime Chica",
        "William Afton",
        "Phone Guy",
        "Candy Cadet",
        "Henry",
        "The Crying Child",
        "The One You Should Not Have Killed",
        "The Bite of '87",
        "Endoskeleton",
        "Lolbit",
        "Vanessa",
        "Rockstar Freddy",
        "Roxanne Wolf",
        "Monty Gator",
        "The Blob",
        "Molten Freddy",
        "Glitchtrap",
        "Sun",
        "Moon",
        "Minireena",
        "El Chip",
        "Egg Baby",
        "Gregory",
        "Elizabeth Afton",
        "Charlotte Emily",
        "Stitchwraith",
        "Fazgoo",
        "Remnant",
        "Purple Guy",
        "Exotic Butters",
    ],
    "YouTube": [
        "PewDiePie",
        "Markiplier",
        "Jacksepticeye",
        "MatPat",
        "StephPat",
        "CaptainSparklez",
        "X33N",
        "TheOdd1sOut",
        "Jaiden Animations",
        "Linus Tech Tips",
        "PeanutButterGamer",
        "VSauce",
        "Dream",
        "MrBeast",
        "Dude Perfect",
        "Olan Rogers",
        "Veritasium",
        "Mark Rober",
        "The Slow Mo Guys",
        "Ryan George",
        "Nile Red",
        "The Dog of Wisdom",
        "YouTube Rewind",
        "ISAB",
        "How Ridiculous",
        "Marques Brownlee",
        "CinemaSins",
        "Three Blue One Brown",
        "WatchMojo",
        "HISHE",
        "Honest Trailers",
        "Oversimplified",
        "Crash Course",
        "Stand Up Maths",
        "ElementAnimation",
        "Ilmango",
        "Studio C",
        "The Try Guys",
        "Tom Scott",
        "The Annoying Orange",
        "Hank Green",
        "Seth Everman",
        "Play Button",
        "YouTube Premium",
        "JacksFilms",
        "The Algorithm",
        "How to Basic",
        "History of the Entire World, I Guess",
        "Presidents play Minecraft",
        "Minecraft Parodies",
        "React Channel",
        "We Are Number One",
        "All Star",
        "Sethbling",
        "ASDF Movie",
        "The Bee Movie but...",
        "Coincidance",
        "Vine Compilation",
        "Shia LaBeouf - Rob Cantor",
        "Just Do It",
        "The Evolution of Dance",
        "Gangnam Style",
        "Charlie Bit My Finger",
        "Chocolate Rain",
        "Rickroll",
        "Nyan Cat",
        "Blue Da Ba Dee",
        "Coffin Dance",
        "Despacito",
        "Baby Shark",
        "Rush E",
        "E",
        "Apology Videos",
        "Out of Context",
        "The YouTube Poop",
        "The Emoji Movie",
        "The YouTube Comment Section",
        "The Deepest Dab",
        "First",
        "The Dislike Button",
        "The Like Button",
        "The Subscribe Button",
        "Unskippable Ads",
        "Compressed Video",
        "YouTube Red",
        "Happy Wheels",
        "How To Videos",
        "YouTube Shorts",
        "Demonetization",
        "Copyright Strikes",
        "IGN",
        "Will Smith",
        "Clickbait",
    ],
    "DC": [
        "Batman",
        "Superman",
        "The Flash",
        "Joker",
        "Harley Quinn",
        "Wonder Woman",
        "Aquaman",
        "Cyborg",
        "Green Lantern",
        "Shazam",
        "Robin",
        "Beast Boy",
        "Raven",
        "Catwomen",
        "Poison Ivy",
        "The Penguin",
        "The Riddler",
        "Two-Face",
        "Bane",
        "Scarecrow",
        "Clayface",
        "Starfire",
        "Deathstroke",
        "Ra's al Ghul",
        "Lex Luthor",
        "Martian Manhunter",
        "Hawkman",
        "Hawkgirl",
        "Supergirl",
        "Green Arrow",
        "Black Canary",
        "The Atom",
        "Kid Flash",
        "John Constantine",
        "Plastic Man",
        "Dr Fate",
        "Firestorm",
        "General Zod",
        "Brainiac",
        "Darkseid",
        "Steppenwolf",
        "Reverse Flash",
        "Zoom",
        "Captain Cold",
        "Cheeta",
        "Ares",
        "The Legion of Doom",
        "Doomsday",
        "The Justice League",
        "Gotham",
        "Metropolis",
        "Lowis Lane",
        "Comissioner Gordon",
        "Iris",
        "Batcave",
        "Batmobile",
        "Krypton",
        "Kryptonite",
        "The Lasso of Truth",
        "The Bat Signal",
        "The Green Lantern Corps",
    ],
    "Disney": [
        "Mickey Mouse",
        "Minnie Mouse",
        "Donald Duck",
        "Daisy Duck",
        "Goofy",
        "Pluto",
        "Pete",
        "Max",
        "Hewey, Dewey, and Louie",
        "Scrooge McDuck",
        "Chip and Dale",
        "Snow White",
        "The 7 Dwarfs",
        "The Evil Queen",
        "The Poisoned Apple",
        "Prince Charming",
        "Cinderella",
        "The Fairy Godmother",
        "The Glass Slipper",
        "The Prince",
        "The Wicked Stepmother",
        "The Wicked Stepsisters",
        "Sleeping Beauty",
        "Maleficent",
        "Pinocchio",
        "Jiminy Cricket",
        "Geppetto",
        "Bambi",
        "Thumper",
        "Bambi's Mother",
        "Flower",
        "The Hunter",
        "Dumbo",
        "The Pink Elephants",
        "Jungle Book",
        "Mowgli",
        "Baloo",
        "Bagheera",
        "King Louie",
        "Shere Khan",
        "Beauty and the Beast",
        "Belle",
        "Beast",
        "Gaston",
        "Lumiere",
        "Cogsworth",
        "Mrs. Potts",
        "Chip",
        "The Enchanted Rose",
        "Lafu",
        "The Little Mermaid",
        "Ariel",
        "Ursula",
        "Flounder",
        "Sebastian",
        "Triton",
        "Prince Eric",
        "Scuttle",
        "Aladdin",
        "Jasmine",
        "Genie",
        "Jafar",
        "Iago",
        "The Sultan",
        "The Cave of Wonders",
        "The Magic Carpet",
        "The Lamp",
        "Abu",
        "Agribah",
        "The Lion King",
        "Simba",
        "Mufasa",
        "Scar",
        "Nala",
        "Timon",
        "Pumbaa",
        "Zazu",
        "Rafiki",
        "Pride Rock",
        "Tarzan",
        "Jane",
        "Clayton",
        "Kala",
        "Hercules",
        "Megara",
        "Hades",
        "Pain and Panic",
        "Phil",
        "The Titans",
        "Pegasus",
        "Zeus",
        "The Hydra",
        "Olympus",
        "Mulan",
        "Mushu",
        "Shan Yu",
        "The Emperor",
        "Li Shang",
        "Yao, Ling, and Chien Po",
        "Cricket",
        "Grandmother Fa",
        "Brother Bear",
        "Koda",
        "Kenai",
        "Rutt and Tuke",
        "Emporer's New Groove",
        "Kuzco",
        "Yzma",
        "Pacha",
        "Chaca",
        "Kronk",
        "Llama",
        "Peter Pan",
        "Tinkerbell",
        "Captain Hook",
        "Wendy",
        "John and Michael",
        "The Lost Boys",
        "The Crocodile",
        "Neverland",
        "Tiger Lily",
        "Lady and the Tramp",
        "Mary Poppins",
        "The 101 Dalmatians",
        "Cruella DeVil",
        "Winnie the Pooh",
        "Tigger",
        "Eeyore",
        "Roo",
        "Piglet",
        "Christopher Robin",
        "The Rabbit",
        "The Owl",
        "Snuffleupagus",
        "Alice in Wonderland",
        "The Mad Hatter",
        "The Cheshire Cat",
        "The White Rabbit",
        "The Queen of Hearts",
        "Tweedle Dee and Tweedle Dum",
        "The Jabberwocky",
        "Robin Hood",
        "Little John",
        "Prince John",
        "Sheriff of Nottingham",
        "Maid Marian",
        "The Great Mouse Detective",
        "Powerline",
        "Sorcerer Mickey",
        "Fantasia",
        "Lilo and Stitch",
        "Stitch",
        "Jumba",
        "Gantu",
        "Lilo",
        "Nani",
        "Pleakley",
        "Chicken Little",
        "Fish",
        "Abby",
        "Ron",
        "Foxy Loxy",
        "Turkey Lurkey",
        "Goosey Loosey",
        "Kirby",
        "Tangled",
        "Rapunzel",
        "Flynn Rider",
        "Mother Gothel",
        "Maximus",
        "The Snuggly Duckling",
        "The Princess and the Frog",
        "Tiana",
        "The Hunchback of Notre Dame",
        "Quasimodo",
        "Esmeralda",
        "Father Dominey",
        "Frozen",
        "Anna",
        "Elsa",
        "Olaf",
        "Kristoff",
        "Sven",
        "Hans",
        "Arendelle",
        "Moana",
        "Maui",
        "Pua",
        "Hei Hei",
        "Big Hero 6",
        "Baymax",
        "Hiro Hamada",
        "Go Go Tomago",
        "Fred",
        "Wasabi",
        "Honey Lemon",
        "Tadashi Hamada",
        "Aunt Cass",
        "Wreck-It Ralph",
        "Vanellope von Schweetz",
        "Fix-It Felix",
        "King Candy",
        "Sugar Rush",
        "Tamora",
        "Qbert",
        "General Hologram",
        "Calhoun",
        "Zootopia",
        "Judy Hopps",
        "Nick Wilde",
        "Flash",
        "Pocahontas",
        "John Smith",
        "Meeko",
    ]
}