# Generated by Django 4.0.5 on 2022-06-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodenameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=30)),
                ('deck', models.ForeignKey(null=True, on_delete=models.deletion.CASCADE, related_name='Cards', to='main.deck')),
                ('source', models.ManyToManyField(blank=True, related_name='Cards', to='main.source'))
            ],
        ),
    ]
