# Generated by Django 4.0.5 on 2022-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='codenamecard',
            name='deck',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
