# Generated by Django 4.0.5 on 2022-06-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodenameCard_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=30)),
                ('deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cards', to='main.deck')),
                ('source', models.ManyToManyField(blank=True, related_name='Cards', to='main.source')),
            ],
        ),
    ]
