# Generated by Django 4.0.5 on 2022-06-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_codenamecard_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodenameCard_1',
        ),
    ]
